- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Clone repository
    git:
      repo: "https://github.com/DarrenJT/DarRepo.git"
      dest: /home/ubuntu/ProgFolder
      clone: yes
      update: yes